version: 2
jobs:
  install:
    docker:
      - image: circleci/node:8.11.3-browsers
    working_directory: ~/repo
    steps:
      # Fetch code
      - checkout

      - run:
          name: Install Bolt
          command: yarn global add bolt

      - run:
          name: Install Dependencies
          command: bolt

      - run:
          name: 



workflows:
  version: 2
  build:
    jobs:
      - install
      - test:
          requires:
            - install